### PR TITLE
hi, i rewrite segnet with 'maxplool index'.

### PR DESCRIPTION
**Pull request by deeptoby**
it works. 
Then the standard fcn‘s input is padding 100pix, i will fix that soon.
haha.

### CODE REVIEW

**Comment by deeptoby** [comment]
can i join your team?
i want to fix them to standard models.
Then i want to add the right PSPNet and DeepLab.

**Comment by bodokaiser** [comment]
@huyalvchuan Thank you! I added you as contributor. Can you also submit some results you obtained with the updated models and add them to the README?

**Comment by deeptoby** [comment]
ok!i have some results.i will add them.

**Comment by bodokaiser** [comment]
Great 👍🏽

**Pull request merged**
